insert into User(name, lastname, mail) values ('Matias', 'Navio', 'matias2@gmail.com')
insert into User(name, lastname, mail) values ('Juan', 'Elias', 'juan@gmail.com')
insert into User(name, lastname, mail) values ('Santiago', 'Federici', 'santiago@gmail.com')
insert into User(name, lastname, mail) values ('Exequiel', 'Carrizo', 'exequiel@gmail.com')
insert into User(name, lastname, mail) values ('Giuliano', 'Blengini', 'gordo@gmail.com')
insert into User(name, lastname, mail) values ('Matias', 'Mondello', 'mondello@gmail.com')